<a href="https://colab.research.google.com/github/rpsing2006-maker/ADV_Python_course/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#advance python day 2

In [1]:
import numpy as np

In [ ]:
# unique() --- return unique numbers from a given array

In [2]:
a = np.array([1,2,2,3,3,3,4,4,4,4,5,5,5,5,5])
a

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])

In [5]:
b = np.unique(a, return_index =True ,return_counts=True)
b

(array([1, 2, 3, 4, 5]), array([ 0,  1,  3,  6, 10]), array([1, 2, 3, 4, 5]))

In [ ]:
# Linspace() --- it will return same gap values in a given range.
#syntax: np.linspace(min, max ,total_numbers)

In [10]:
a = np.linspace(0,5,3)
a

array([0. , 2.5, 5. ])

In [ ]:
#operations on array

In [11]:
a = np.arange(1,11,3) #np.arange(min,max,step_number)
a

array([ 1,  4,  7, 10])

In [ ]:
#reshaping the array
#n(row) * n(column) = n(Total_elements)
#5 * x = 20
#x = 20/5 =4

In [12]:
a = np.random.randint(1,50,12)
a

array([35, 38, 28,  7, 20, 19, 16, 15, 12, 23, 47,  4])

In [ ]:
#1*12 , 12*1
#2*6 , 6*2
#3*4 , 4*3

In [13]:
a.reshape(2,6)

array([[35, 38, 28,  7, 20, 19],
       [16, 15, 12, 23, 47,  4]])

In [14]:
a.reshape(3,4)

array([[35, 38, 28,  7],
       [20, 19, 16, 15],
       [12, 23, 47,  4]])

In [15]:
a.reshape(-1,6)

array([[35, 38, 28,  7, 20, 19],
       [16, 15, 12, 23, 47,  4]])

In [17]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [18]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [20]:
a+b

array([[ 6,  8],
       [10, 12]])

In [21]:
a-b

array([[-4, -4],
       [-4, -4]])

In [23]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [24]:
a.dot(b) #matrix multiplication

array([[19, 22],
       [43, 50]])

In [27]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [33]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(np.sum(a))
print(np.sum(a,axis =0))
print(np.sum(a,axis =1))

45
[12 15 18]
[ 6 15 24]


In [ ]:
#hstack and vstack

In [35]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

print(np.hstack((a,b,c)))
print(np.vstack((a,b,c)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#!!!! practice questions !!!!

In [38]:
#array using numpy
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [39]:
#array of 10 random integers
a = np.random.randint(1,100,10)
a

array([41,  8, 71, 50, 81, 75, 22, 93, 75, 24])

In [40]:
#array of elemnents from 10 to 20
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
#array wich contains value 5 10 times
a = np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [44]:
#create a 1d array and convert into 3X3 matrix
a = np.arange(1,10)
print(a)
a = a.reshape(3,3)
a

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#2d array of size 3*3 but all elements should be in betwenen 0 and 1
a = np.linspace(0,1,9).reshape(3,3)
a

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [50]:
a = np.arange(1,5)
b = np.arange(5,9)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
